### ISSUE TITLE
Can VirtualizedList also support offsetFromStart?

### ISSUE THREAD

**Issue by Yria** [bamlab/react-tv-space-navigation#162]
We want the exact same functionality as offsetFromStart in ScrollView to be present in VirtualizedList.

I tried to fix it, but it didn't work.

```
export const SpatialNavigationVirtualizedList = typedMemo(
  typedForwardRef(
    <T,>(
      props: SpatialNavigationVirtualizedListWithScrollProps<T> & PointerScrollProps,
      ref: ForwardedRef<SpatialNavigationVirtualizedListRef>,
    ) => {
      return (
        <SpatialNavigationNode
          alignInGrid={props.isGrid ?? false}
          orientation={props.orientation ?? 'horizontal'}
          additionalOffset={props.offsetFromStart ?? 0}
        >
          <SpatialNavigationVirtualizedListWithScroll<T> {...props} ref={ref} />
        </SpatialNavigationNode>
      );
    },
  ),
);
```

**Comment by pierpo** [comment]
Hey @Yria! It's a good point, but actually the VirtualizedList scroll behaviour is different 🙈
It's a state driven scroll with pre-computed positions. It would be trickier to control it with an offset parameter, because we're manually computing the max scroll position in case we reach the end of the list (it's all implemented with CSS translates 😮 ). Same for the min scroll position.

What I wish we implemented (and we might do later): a parameter to adjust how shifted the elements are in the list.

Right now, we have stick-to-start or stick-to-end. There's a PR for stick-to-center.
But I wish we could give a percentage. Stick to start would be 0%, stick to end would be 100%, stick to center 50%. And you'd be free to put any continuous value.

Would that solve your use case?

**Comment by Yria** [comment]
@pierpo 
Thank you for your reply.
With ScrollView, the item tries to move within the scrolling content.
However, in the case of a ListView, the item will always try to stay where the focus is on.
My goal was to eliminate the difference between the two, so I don't think it would make much difference if the logic was different.
Thanks again for the help.
