### ISSUE TITLE
React js

### ISSUE THREAD

**Issue by AmirKaftari** [bamlab/react-tv-space-navigation#26]
this can be use for react js app ?

**Comment by pierpo** [comment]
Hey!

That is a very good point. We had considered it, and we ended up not supporting React JS.
We should have stated it somewhere.

It could be super nice, and it's still something that can be done, but it's quite some work unfortunately :cry: 
We haven't planned it yet!

**Comment by pierpo** [comment]
Closing as we won't support pure ReactJS for now. But we're considering it for the future. I think the library will evolve as the React Native TV ecosystem evolves. My hope is that this library becomes useless because the native focus system becomes good enough 😊 

In that case, we'll still need the library for the web version of a TV app!
