### ISSUE TITLE
Using React.StrictMode will cause problems.

### ISSUE THREAD

**Issue by Yria** [bamlab/react-tv-space-navigation#49]
**Describe the bug**
Using React.StrictMode will cause problems.

**To Reproduce**
react-tv-space-navigation/packages/example/web/index.tsx
```tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from '../App';
import './fonts.css';

createRoot(document.getElementById('root') as HTMLElement).render(<React.StrictMode><App /></React.StrictMode>);
```

**Screenshots**
<img width="494" alt="image" src="https://github.com/bamlab/react-tv-space-navigation/assets/1844282/76c477b4-8b07-46a7-b345-ea74b1ee2cd1">

**Version and OS**
 - Library version: 1.3.0

**Comment by pierpo** [comment]
Hi,

Indeed, we had not thought of this problem. I tend to forget about strict mode.
I think the recommendation would be to disable it 😢 

There are some hacks under the hood, because syncing React's tree with LRUD's tree is not trivial at all. And I'm not really surprised that these hacks break under StrictMode (more details [in our talk](https://www.youtube.com/watch?v=Asn1TmCH2b0) if you want to know why)

**Comment by Yria** [comment]
Thank you for your response.
The problem is caused by the difference between render order and useEffect order.

**Comment by pierpo** [comment]
Yeah, because of the nature of these tricks I fear we'll never be able to support StrictMode.
We should add it in the README!

**Comment by pierpo** [comment]
Hi!

It turns out, this might work some day. I'm getting rid of the dirty `useBeforeMountEffect`, which was one of the main culprits for the strict mode to not work.

I managed to make the app run with a thousand warnings haha
(apart from the warnings, everything works well)

I can't commit to anything but it's not as hopeless as I thought it would be 😁

**Comment by pierpo** [comment]
Hey! I just tried to enable the React Strict Mode on the example app, and it turns out that it works 😁  No errors.
One thing does not work properly though: all virtualized lists are not starting at the element 0 😂  I'll have a look at this later.

But it means that you can now enable Strict Mode in a debug environment 😁
